HZY.Admin/Controllers/Framework/LoginController.cs
using System.Threading.Tasks;
using HZY.Admin.Model.Dto;
using HZY.Admin.Services.Framework;
using HZY.Framework.Controllers;
using HZY.Framework.Model;
using Microsoft.AspNetCore.Mvc;

namespace HZY.Admin.Controllers.Framework
{
    public class LoginController : AdminBaseController<SysUserService>
    {
        private readonly AccountService _accountService;

        public LoginController(SysUserService defaultService, AccountService accountService) : base(defaultService)
        {
            _accountService = accountService;
        }

        [HttpGet(nameof(Index))]
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 退出登录
        /// </summary>
        /// <returns></returns>
        [HttpGet(nameof(Out))]
        public IActionResult Out()
        {
            this._accountService.RemoveToken();
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// 检查帐户并获取 token
        /// </summary>
        /// <param name="authUserDto">Dto</param>
        /// <returns></returns>
        [HttpPost("Check")]
        public async Task<ApiResult> CheckAccountAsync([FromBody] AuthUserDto authUserDto)
        {
            var token = await this.DefaultService
                .CheckAccountAsync(authUserDto.UserName, authUserDto.UserPassword, authUserDto.LoginCode);

            const string tokenType = "Bearer ";

            return this.ResultOk(new {token, tokenType});
        }
    }
}

HZY.Admin/Views/Shared/_Aside.cshtml
@{
    var menuList = ViewData["menuList"] as List<Dictionary<string, object>>;

}
@functions{

    void CreateMenu(List<Dictionary<string, object>> menus, List<Dictionary<string, object>> menuAll)
    {
        //
        foreach (var item in menus)
        {
            var id = item["id"];
            var title = item["name"];
            var href = item["path"];
            var icon = item["icon"];
            var isClose = item["isClose"];
            var childless = item["children"] as List<Dictionary<string, object>>;
            var isFirst = menuAll.IndexOf(item) == 0;
            if(childless==null) continue;
            if (childless.Count > 0)
            {
                <li class="@(isFirst ? "mm-active" : "")">
                    <a class="has-arrow" href='javascript:;' aria-expanded="@(isFirst ? "true" : "false")">
                        <i class="@icon"></i><span>@title</span>
                    </a>
                    <ul class="mm-collapse @(isFirst ? "mm-show" : "")">
                        @foreach (var children in childless)
                        {
                            id = children["id"];
                            title = children["name"];
                            href = children["path"];
                            icon = children["icon"];
                            isClose = children["isClose"];
                            childless = children["children"] as List<Dictionary<string, object>>;
                            if(childless==null) continue;
                            @if (childless.Count > 0)
                            {
                                var menu = new List<Dictionary<string, object>>();
                                menu.Add(children);
                                CreateMenu(menu, menuAll);
                            }
                            else
                            {
                                <li hzy-id="@id" hzy-title="@title" hzy-href="@href" hzy-isClose="@(isClose.ToInt32()==1?"true":"false")">
                                    <a href="javascript:void('@(href)');">
                                        <i class="@icon"></i><span>@title</span>
                                    </a>
                                </li>
                            }
                        }
                    </ul>
                </li>
            }
            else
            {
                <li hzy-id="@id" hzy-title="@title" hzy-href="@href" hzy-isClose="@(isClose.ToInt32()==1?"true":"false")">
                    <a href="javascript:void('@(href)');">
                        <i class="@icon"></i><span>@title</span>
                    </a>
                </li>
            }
        }
    }

}

<!--menu 菜单-->
<nav class="hzy-menu sidebar-nav sidebar-nav-max">
    <ul class="metismenu" id="hzyAdminMenu">
        @{CreateMenu(menuList,menuList);}
    </ul>
</nav>

HZY.Admin/Views/Shared/_Footer.cshtml
@*<footer class="main-footer">
    <strong>版权 &copy; 2017-2020 <a href="https://gitee.com/hzy6" target="_blank">HZY.AdminRazor</a>.</strong>
    保留所有权利.
    <div class="float-right d-none d-sm-inline-block">
        <b>版本</b> 1.0.0
    </div>
</footer>*@

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->

HZY.Admin/Views/Shared/_Layout.cshtml
@inject AppConfiguration AppConfiguration
@{
    ViewData["HzyAdminUIPath"] = "/admin/hzyAdminUI/";
}

<!DOCTYPE html>
@* class="animation-fade" *@
<html lang="zh">
<head>
    <script>
        var _hmt = _hmt || [];
        (function () {
            var hm = document.createElement("script");
            hm.src = "https://hm.baidu.com/hm.js?90d9b1016c84f436fc9b4b318f5a0ff9";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();
    </script>
    <meta name="keywords" content="hzyadmin,hzy,HZY,HZY.AdminRazor,hzyadminspa,HZY.AdminSpa">
    <meta charset="UTF-8">
    <!-- 避免IE使用兼容模式 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <!-- 移动设备 viewport -->
    <meta name="viewport"
          content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no,minimal-ui">
    <!-- 360浏览器默认使用Webkit内核 -->
    <meta name="renderer" content="webkit">
    <!-- 禁止搜索引擎抓取 -->
    <meta name="robots" content="nofollow">
    <!-- 禁止百度SiteAPP转码 -->
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <!-- Chrome浏览器添加桌面快捷方式（安卓） -->
    <meta name="mobile-web-app-capable" content="yes">
    <!-- Safari浏览器添加到主屏幕（IOS） -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="">
    <!--[if lt IE 9]>
        <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
        <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <title>@ViewData["Title"] - @AppConfiguration.AppTitle</title>
    <link rel="shortcut icon" href="/favicon.ico">
    <!--菜单-->
    <link href="@ViewData["HzyAdminUIPath"]libs/metismenu-master/metisMenu.min.css" rel="stylesheet"/>
    <!--web icons 图标库-->
    <link href="@ViewData["HzyAdminUIPath"]css/web-icons-master/css/web-icons.css" rel="stylesheet"/>
    <!--样式-->
    <link href="@ViewData["HzyAdminUIPath"]css/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="@ViewData["HzyAdminUIPath"]css/bootstrap.min.css" rel="stylesheet"/>
    <link href="@ViewData["HzyAdminUIPath"]css/core.css" rel="stylesheet"/>
    <link href="@ViewData["HzyAdminUIPath"]css/site.css" rel="stylesheet"/>
    <!--选项卡-->
    <link href="@ViewData["HzyAdminUIPath"]libs/hzyBootStrapTabs/index.css" rel="stylesheet"/>
    <!--主页面-->
    <link href="@ViewData["HzyAdminUIPath"]css/hzyAdminUI.css" rel="stylesheet"/>
    <!--element ui-->
    <link rel="stylesheet" href="~/admin/libs/elementui/lib/theme-chalk/index.css">
    <!--框架样式-->
    <link href="~/admin/css/hzyAdmin.css" rel="stylesheet"/>
    @RenderSection("Styles", required: false)
</head>
<body>

@RenderBody()

<!--脚本-->
<script src="@ViewData["HzyAdminUIPath"]libs/jquery/jquery-3.2.1.min.js"></script>
<!--jquery bolb 文件下载扩展-->
<script src="~/admin/libs/axios.min.js"></script>
<!---->
<script src="@ViewData["HzyAdminUIPath"]libs/bootstrap/js/bootstrap.bundle.min.js"></script>
<!--metisMenu 菜单-->
<script src="@ViewData["HzyAdminUIPath"]libs/metismenu-master/metisMenu.min.js"></script>
<!--选项卡-->
<script src="@ViewData["HzyAdminUIPath"]libs/hzyBootStrapTabs/index.js"></script>
<!--主页面-->
<script src="@ViewData["HzyAdminUIPath"]js/hzyAdminUI.js"></script>
<!-- vue -->
<script src="~/admin/libs/vue.js"></script>
<!--element ui-->
<script src="~/admin/libs/elementui/lib/index.js"></script>
<!--layer 弹框插件-->
<script src="~/admin/libs/layer/layer.js"></script>
<!-- hzyAdmin -->
<script src="~/admin/js/hzyAdmin.js"></script>
@RenderSection("Scripts", required: false)
</body>
</html>

HZY.Admin/Views/Shared/_Navbar.cshtml
@inject AppConfiguration AppConfiguration
<header class="hzy-header-skin-blue">
    <div class="hzy-header-left">
        <ul>
            <!--fas fa-indent-->
            <li class="hzy-headerhover" onclick="hzyAdminUI.menu.toggle();">
                <a href="javascript:void(0)">
                    <i class="fas fa-outdent"></i>
                </a>
            </li>
            <li class="hzy-headerhover hzy-logo"><a>@AppConfiguration.AppTitle</a></li>
        </ul>
    </div>
    <div class="hzy-header-right d-none d-lg-block">
        <ul>
            <li class="hzy-headerhover" onclick="hzyBootStrapTabs.loadCurrentPage()">
                <a href="javascript:;">
                    <i class="fas fa-redo"></i>
                </a>
            </li>
            <li class="hzy-headerhover" onclick="$('#examplePositionSidebar').modal()">
                <a href="javascript:;">
                    <i class="fas fa-layer-group"></i>
                </a>
            </li>
            <!--fa fa-compress-->
            <li class="hzy-headerhover">
                <a href="javascript:;"
                   onclick="hzyAdminUI.fullScreen.handleFullScreen(this)"><i class="fas fa-expand"></i></a>
            </li>
            <li class="hzy-headerhover">
                <a href="@Url.Action("Out", "Login")">
                    <span><i class="fas fa-user"></i>&nbsp;@ViewData["UserName"]</span>&nbsp;&nbsp;<i class="fas fa-sign-out-alt"></i>
                </a>
            </li>
        </ul>
    </div>
    <div class="hzy-header-right d-lg-none">
        <ul>
            <li class="hzy-headerhover">
                <a href="@Url.Action("Out", "Login")"><i class="fas fa-sign-out-alt"></i></a>
            </li>
        </ul>
    </div>
</header>